### PR TITLE
Add support for Symfony 6 components

### PR DESCRIPTION
**Pull request by racastellanosm**
Adding support for Symfony 6.x option resolver component to avoid failing installs on Symfony 6.x projects.

### CODE REVIEW

**Comment by racastellanosm** [comment]
Hi @dantleech thanks for you project.

This PR is intended also to produce a new tag for `phpbench:phpbench`  main project because as today it's has a installation conflict with projects with Symfony 6.x 

Do you need that i open a new PR on `phpbench:phpbench` project referencing this issue?

Regards

**Comment by dantleech** [comment]
ach, I thought PHPBench already supported 6.x but I guess options resolver was indeed held back.

**Comment by dantleech** [comment]
Tagged 2.2.1, should be fine now i guess

**Comment by racastellanosm** [comment]
Works perfect now! Thanks.

**Pull request merged**
